Repository takluyver/pynsist, pull requests merged in 2020-11, with the labels that each got.

#210 No ABI suffix in wheel names on Python >=3.8
  nsist/tests/test_pypi.py
  nsist/wheels.py
Labels: bug

#213 Better error messages for invalid entry points
  nsist/__init__.py
  nsist/tests/test_misc.py
Labels: enhancement

#215 removed dead links from example applications
  doc/examples.rst
Labels: documentation
